name: CP_App
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter
  shimmer: ^1.0.1
  liquid_swipe: ^1.5.0
  percent_indicator: "^2.1.7+2"
  foldable_sidebar: ^1.0.0
  flutter_swiper: ^1.1.6
  url_launcher: ^5.7.10
  bottom_navy_bar: ^5.5.0
  cloud_firestore: ^0.14.3
  firebase_core: ^0.5.0
  intl: ^0.16.1
  pie_chart: ^4.0.1
  curved_navigation_bar: ^0.3.4
 
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^4.3.2+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - images/cboy.png
      - images/bg2.jpeg
      - images/hrbottom.png
      - images/x1.png
      - images/bg3.jpeg
      - images/c1.jpg
      - images/d1.png
      - images/TCplat.jpg
      - images/mynewcf.png
      - images/tc11.png
      - images/mynewcc.png
      - images/lc12.png
      - images/x4.png
      - images/x13.jpeg
      - images/x7.jpg
      - images/languages.jpg
      - images/x15.png
      - images/cff1.jpg
      - images/qmark.jpg
      - images/qmark2.png
      - images/d2.png
      - images/c3.jpg
      - images/ac1.png
      - images/sp1.png
      - images/tc1.png
      - images/c2.jpg
      - images/C.jpg
      - images/st1.jpg
      - images/st2.jpg
      - images/st3.jpg
      - images/st4.png
      - images/st5.png
      - images/cw25.png
      - images/st6.jpg
      - images/st7.png
      - images/st8.png
      - images/st10.png
      - images/correctanswer.png
      - images/quizui3.jpg
      - images/linkedlist.png
      - images/graph.png
      - images/binarytree.png
      - images/stack.png
      - images/queue.jpg
      - images/C++.jpg
      - images/cf1.png
      - images/Python.jpg
      - images/Main_prob.jpg
      - images/prepage1.png
      - images/prepage2.png
      - images/prepage3.png
      - images/prepage4.png
      - images/Cardback.jpg
      - images/lastchoice.jpg
      - images/black.jpg
      - images/ui6.jpg
      - images/cofused.png
      - images/java.png
      - images/choice.jpg
      
      - images/swipeatproblem.png
      - images/swipe.png
      - images/java12.jpg
      
      - images/atcoder.png
      - images/codeforces.jpg
      - images/Codechef.jpeg
      - images/hackerrank.png
      - images/helogo.jpg
      - images/hackerearth.png
      - images/leetcode.jpeg
      - images/google.jpg
      - images/ds.jpg
      - images/py.png
      - images/timespace.png
      - images/quiz.jpg
      - images/stl.jpg
      - images/problems.jpg
      - images/top_draw.jpg
      - images/img1.jpg
      - images/a1.png
      - images/s1.png
      - images/m2.png
      - images/fund1.png
      - images/op.jpg
      - images/op2.jpg
      - images/ui2.jpg
      - images/op3.jpg
      - images/op6.png
      - images/x3.png
      - images/sorting.png
      - images/search.png
      - images/array.jpg
      - images/string.jpg
      - images/search.png
      - images/maths2.jpg
      - images/hashmap.jpg
      - images/sorting.png
      - images/wronganswer.png 
      - images/tree1.png
      - images/tree1.jpeg
      - images/tree2.png
      - images/tree3.png
      - images/tree4.png
      - images/tree5.png
      - images/inorder1.jpg
      - images/preorder.jpg
      - images/postorder.jpg
      - images/crop.jpg
      - images/applogo.png
     
      - images/finallogo.jpg
      - images/codingplatform.png
      - images/q1.png
      - images/q2.png
      - images/q3.png
      - images/q4.png
      - images/g1.png
      - images/g2.png
      - images/g3.png
      - images/g4.png
      - images/g5.png
      - images/g6.png
      - images/g7.png
      - images/g8.png
      - images/q5.png
      - images/q6.png
      - images/q7.png
      - images/q8.png
      - images/q9.png
      - images/q10.png
      - images/q11.png
      - images/q12.jpg
      - images/q13.png
      - images/L1.png
      - images/L2.png
      - images/L3.png
      - images/L4.png
      - images/L5.png
      - images/L6.png
      - images/L7.png
      - images/L8.png
      - images/L9.png
      - images/L10.png
      - images/L11.png
      - images/L12.png
      - images/L13.png
      - images/L14.png
      - images/L15.png
      - images/L16.png
      - images/L17.png
      - images/L18.png
      - images/L19.png
      - images/L20.png
      - images/L21.png
      - images/L22.png
      - images/cc.jpg
      - images/halogo.png
      - images/cclogo.png
      - images/spojlogo.png
      - images/cwlogo.png
      - images/lclogo.png
      - images/cflogo.png
      - images/tclogo.jpeg
      - images/aclogo.png
      - images/ts1.png
      - images/ts2.png
      - images/ts3.png
      - images/ts4.png
      - images/ds1.jpg
      - images/theta.png
      - images/omega.png
      - images/bigo.png
      - images/base.png
      - images/ts5.png
      - images/CSES2.jpg
      - images/pros.jpg
      - images/adv.jpg
      - images/cons.jpg

    
  
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    
    - family: PatuaOne
      fonts:
        - asset: fonts/PatuaOne-Regular.ttf    
    
    - family: Quattrocento
      fonts:
        - asset: fonts/Quattrocento-Regular.ttf
    - family: Signika
      fonts:
        - asset: fonts/Signika-Regular.ttf
       
    
    - family: ZillaSlab
      fonts:
        - asset: fonts/ZillaSlab-BoldItalic.ttf
    
    - family: Goldman
      fonts:
        - asset: fonts/Goldman-Bold.ttf


    - family: HammersmithOne
      fonts:
        - asset: fonts/HammersmithOne-Regular.ttf

    - family: AlfaSlabOne
      fonts:
        - asset: fonts/AlfaSlabOne-Regular.ttf

    - family: BreeSerif
      fonts:
        - asset: fonts/BreeSerif-Regular.ttf

    - family: CreteRound
      fonts:
        - asset: fonts/CreteRound-Regular.ttf

    - family: ConcertOne
      fonts:
        - asset: fonts/ConcertOne-Regular.ttf  

    - family: Grandstander
      fonts:
        - asset: fonts/Grandstander-VariableFont_wght.ttf
    
    - family: Fredoka One
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf

    - family: Acme
      fonts:
        - asset: fonts/Acme-Regular.ttf
  
    - family: Ranchers
      fonts:
        - asset: fonts/Ranchers-Regular.ttf

    - family: Monoton
      fonts:
        - asset: fonts/Monoton-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: icons/custom_icons.ttf
    - family: PaytoneOne
      fonts:
        - asset: fonts/PaytoneOne-Regular.ttf


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
